export const SAVE_GEOHASH = 'SAVE_GEOHASH'
export const GET_GEOHASH = 'GET_GEOHASH'
export const GET_SHOPINFO_LENGTH = 'GET_SHOPINFO_LENGTH'
export const SAVE_SHOPINFO_LENGTH = 'SAVE_SHOPINFO_LENGTH'
